Tasks linker
fedor-ivn/grader pull request #2
Opened 2023-06-17 16:32 UTC by fedor-ivn

The script symlinks tasks from the initial tree-like structure to the `tasks` folder.

2023-06-18 06:57 UTC, ruca905 requested changes

2023-06-18 06:57 UTC, ruca905 commented on task_directory.py
> +    TASK_FILES = [
А вообще, это используется хоть где-то? Я не вижу

2023-06-18 06:57 UTC, ruca905 commented on task_directory.py
> +            print(f"Symlink {name} already exists")
А тут не должно быть что-то типа throw Exception (f"Symlink {name} already exists")?

2023-06-18 06:57 UTC, ruca905 commented on task_directory.py
> +    def __init__(self, source_directory, target_path):
Давайте писать типы у переменных в аргументах функций. Совсем не понятно, что это

2023-06-18 06:57 UTC, ruca905 commented on task_directory.py
> +    def __init__(self, source_tree, depth):
Хочется типов тоже

2023-06-18 06:57 UTC, ruca905 commented on task_directory.py
> +    def _traverse_directory(self, path, remaining_depth):
Егор считает, что приватные функции это плохо
https://www.yegor256.com/2017/02/07/private-method-is-new-class.html

Не фанатично, но считает. То есть надо будет суметь обосновать, почему бы не вынести это в отдельный класс.

2023-06-18 06:57 UTC, ruca905 commented on task_directory.py
> +        self.symlinks.healthcheck()
Выглядит как какая-то сложная логика в конструкторе

2023-06-18 07:19 UTC, fedor-ivn commented on task_directory.py
> +    TASK_FILES = [
будет использоваться

это просто набор файлов, который должен в директории быть обязательно

2023-06-18 07:20 UTC, fedor-ivn commented on task_directory.py
> +    def _traverse_directory(self, path, remaining_depth):
ну это же рекурсивная функция, куда ее деть?

2023-06-18 07:22 UTC, fedor-ivn commented on task_directory.py
> +tasks = TasksDirectory(
это для теста пока что)

2023-06-18 07:40 UTC, fedor-ivn commented on task_directory.py
> +    TASK_FILES = [
можешь предложить, как переписать?

2023-06-18 07:42 UTC, fedor-ivn commented on task_directory.py
> +    def __init__(self, source_directory, target_path):
хорошо, давай

не писал типы только потому что егор в рубях их тоже не пишет

2023-06-18 07:42 UTC, fedor-ivn commented on task_directory.py
> +        self.symlinks.healthcheck()
перепишу может быть

2023-06-18 07:48 UTC, ruca905 commented on task_directory.py
> +    TASK_FILES = [
Понять бы, что это сначала) Но вообще, в общем надо завернуть эти константы в объекты

2023-06-18 19:23 UTC, ruca905 requested changes

2023-06-18 19:23 UTC, ruca905 commented on task/task.py
> +        self.task_path = task_path
А что такое task? Оно в итоге так и будет определяться только task_path? Или это какая-то более сложная абстракция?

2023-06-18 19:23 UTC, ruca905 commented on task/symlink.py
> +    def task_path(self) -> str:
А оно точно здесь? Может в Task перенести? Или я что то не понимаю

2023-06-18 19:23 UTC, ruca905 commented on task/symlink.py
> +    def name(self) -> str:
Выглядит как приватный метод, который совершенно не относится к интерфейсу TaskSymlink
Если так, то надо вынести в отдельный класс

2023-06-18 19:23 UTC, ruca905 commented on task/symlink.py
> +            print(f"Symlink {name} already exists")
А почему не выкинуть exception? Или может просто игнорировать?

2023-06-18 19:23 UTC, ruca905 commented on task/symlink.py
> +    def healthcheck(self) -> None:
Вообще, странное название. Но если больше нет идей, то надо вместе, наверное, подумать

2023-06-20 15:16 UTC, fedor-ivn commented on .devcontainer/devcontainer.json
>  	"features": {
нет, не должны

у нас с дамиром общие конфиги для среды разработки

2023-06-20 15:16 UTC, fedor-ivn commented on __pycache__/main.cpython-311.pyc
это да, уже удалили вроде

2023-06-20 15:18 UTC, fedor-ivn commented on task/symlink.py
> +    def name(self) -> str:
в какой?

2023-06-20 20:08 UTC, merged